#!/bin/sh
## Basic wrapper for lncli.

## Confugration Settings.
RPC_HOST="localhost:10010"
MACAROON_PATH="$(pwd)/data/chain/bitcoin/regtest/admin.macaroon"

## Build Configuration String.
DEFAULT_CONF="--rpcserver $RPC_HOST --macaroonpath $MACAROON_PATH"

## Run LNCLI with config and passed arguments.
./bin/lncli $DEFAULT_CONF $@
