#!/bin/sh
## Basic wrapper for lncli.

## Confugration Settings.
RPC_HOST="localhost:10009"
NETWORK="regtest"
MACAROON_PATH="$(pwd)/data/chain/bitcoin/$NETWORK/admin.macaroon"

## Build Configuration String.
DEFAULT_CONF="--network $NETWORK --rpcserver $RPC_HOST --macaroonpath $MACAROON_PATH"

## Run LNCLI with config and passed arguments.
./lncli $DEFAULT_CONF $@
